version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: weekly
    time: "13:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: anyhow
    versions:
    - "> 1.0.43, < 2"
  - dependency-name: inferno
    versions:
    - "> 0.10.0, < 0.11"
  - dependency-name: opener
    versions:
    - "> 0.5.0, < 0.6"
  - dependency-name: signal-hook
    versions:
    - "> 0.3.10, < 0.4"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    time: "06:28"
